#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Python virtualenvwrapper
export PROJECT_HOME="$HOME/Code"

# Java
if [[ -d /usr/libexec/java_home ]]; then
  export JAVA_HOME="$(/usr/libexec/java_home)"
fi

# zlib installed from homebrew is keg only and needs compiler directives updated.
if [[ -d "/usr/local/opt/zlib" ]]; then
  export LDFLAGS="${LDFLAGS} -L/usr/local/opt/zlib/lib"
  export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/zlib/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/zlib/lib/pkgconfig"
fi
if [[ -d "/opt/homebrew/opt/zlib" ]]; then
  export LDFLAGS="${LDFLAGS} -L/opt/homebrew/opt/zlib/lib"
  export CPPFLAGS="${CPPFLAGS} -I/opt/homebrew/opt/zlib/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/zlib/lib/pkgconfig"
fi

# libffi is needed for older ruby versions
if [[ -d "/usr/local/opt/libffi" ]]; then
  export LDFLAGS="${LDFLAGS} -L/usr/local/opt/libffi/lib"
  export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/libffi/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"
fi
if [[ -d "/opt/homebrew/opt/libffi" ]]; then
  export LDFLAGS="${LDFLAGS} -L/opt/homebrew/opt/libffi/lib"
  export CPPFLAGS="${CPPFLAGS} -I/opt/homebrew/opt/libffi/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/libffi/lib/pkgconfig"
fi

# openssl
if [[ -d "/usr/local/opt/openssl@1.1" ]]; then
  export LDFLAGS="${LDFLAGS} -L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/openssl@1.1/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl@1.1/lib/pkgconfig"
fi
if [[ -d "/opt/homebrew/opt/openssl@1.1" ]]; then
  export LDFLAGS="${LDFLAGS} -L/opt/homebrew/opt/openssl@1.1/lib"
  export CPPFLAGS="${CPPFLAGS} -I/opt/homebrew/opt/openssl@1.1/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"
fi
if [[ -d "/usr/local/opt/openssl@3" ]]; then
  export LDFLAGS="${LDFLAGS} -L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/openssl@3/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl@3/lib/pkgconfig"
fi
if [[ -d "/opt/homebrew/opt/openssl@3" ]]; then
  export LDFLAGS="${LDFLAGS} -L/opt/homebrew/opt/openssl@3/lib"
  export CPPFLAGS="${CPPFLAGS} -I/opt/homebrew/opt/openssl@3/include"
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/openssl@3/lib/pkgconfig"
fi

# Export 1Password SSH Auth Socket information
if [[ -e $HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ]]; then
  export SSH_AUTH_SOCK=$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
fi
